# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

lane :build do
  flutter(action: 'l10n',
          l10n_strings_file: 'lib/flutter/localization.dart',
          l10n_strings_locale: 'en',
          l10n_reformat_arb: true)
  flutter(action: 'format')
  flutter(action: 'analyze')
end

platform :android do
  lane :build do
    flutter(action: 'build', debug: true)
  end

  lane :publish do
    flutter(action: 'build').values.first
    supply(
      track: 'internal',
      apk: lane_context[SharedValues::FLUTTER_OUTPUT_APK],
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end
end

platform :ios do
  lane :build do
    flutter(action: 'build', debug: true)
  end
end

# vim: ft=ruby
