# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

lane :build do
  flutter(
    action: 'l10n',
    l10n_strings_file: 'lib/flutter/localization.dart',
    l10n_strings_locale: 'en',
    l10n_reformat_arb: true,
  )
  flutter(action: 'format')
  flutter(action: 'analyze')
end

platform :android do
  lane :build do
    flutter(
      action: 'build',
      git_version: true,
      debug: true,
    )
  end

  lane :publish do
    flutter(
      action: 'build',
      git_version: true,
    )
    supply(
      track: 'internal',
      apk: lane_context[SharedValues::FLUTTER_OUTPUT_APK],
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end
end

platform :ios do
  lane :build do
    # Set up OS X keychain and switch match to readonly model. This command has
    # no effect outside CI.
    setup_travis

    match(
      type: 'development',
      app_identifier: 'org.dasfoo.delern.debug',
    )
    flutter(
      action: 'build',
      git_version: true,
      debug: true,
    )
  end

  lane :publish do
    setup_travis
    match(
      type: 'appstore',
      app_identifier: 'org.dasfoo.delern',
    )
    # Build the app to:
    # - add version
    # - switch to release mode
    flutter(
      action: 'build',
      git_version: true,
      # TODO(dotdoom): since this changes Podfile.lock and other files to
      #                symlink the release version of packages, we have to clear
      #                dirty mark.
      git_version_dirty_mark: '',
    )
    gym(silent: true)
    pilot(
      ipa: 'build/Runner.ipa',
      skip_submission: true,
    )
  end
end

# vim: ft=ruby
